### ISSUE TITLE
Could not resolve dependency in react 18

### ISSUE THREAD

**Issue by hushino** [streamich/react-use#2329] opened 2022-05-16 02:11 UTC
![image](https://user-images.githubusercontent.com/7049470/168508253-7fe1e1bb-5bcc-47ba-b0cf-8010e95b0304.png)

remove the limit of react, bruh is obvious that cant broke anything

**Comment by carolinapowers** [comment] 2022-05-17 21:15
Having the same issue. Trying to update to React 18 but ` ERROR  react-use@17.3.2 requires a peer of react@^16.8.0  || ^17.0.0 but version 18.1.0 was installed.`.

**Comment by veloek** [comment] 2022-05-19 07:27
Duplicate of #2311

**Closed** 2022-05-20 12:10 UTC
