### ISSUE TITLE
TypeScript build fails

### ISSUE THREAD

**Issue by j-f1** [streamich/react-use#87] opened 2018-12-31 13:25 UTC
I’ve enabled the `strict` option in my `tsconfig.json`, and installing this package results in an error because it can’t find types for the `useCallbag` hook, even though I don’t use that hook. It seems to be trying to import the types for the `use-callbag` package, which don’t exist. Can you fix this error?

**Comment by benneq** [comment] 2019-01-31 02:37
I have similar issues:

```
Could not find a declaration file for module 'use-callbag'. 
Could not find a declaration file for module 'use-onclickoutside'. 
Could not find a declaration file for module 'react-wait'
```

Maybe those typings should be a hard dependency for `react-use`?

**Comment by streamich** [comment] 2019-01-31 14:53
This is not a solution, but I think if you import individual hooks like

```js
import myHook from 'react-use/lib/myHook';
```

it should work, or doesn't it?

**Comment by benneq** [comment] 2019-01-31 15:00
Yes this does work, but isn‘t very nice to use

**Comment by streamich** [comment] 2019-01-31 15:05
Well I'm using that approach, and that's why I haven't seen this TypeScript error and haven't had incentive to fix it, sorry for that 😃

**Comment by benneq** [comment] 2019-01-31 15:07
But using this, you won‘t get automatic imports in VSCode ;)

**Comment by streamich** [comment] 2019-03-26 15:58
`use-callbag` and `use-onclickoutside` are not part of dependencies anymore. Do you still see this error?

**Comment by dcporter** [comment] 2019-07-16 19:55
Yes — `react-wait` is causing problems (looks like it has an `@types` ([here](https://www.npmjs.com/package/@types/react-wait))! 🎉), as are `usePermission`’s own types (several are not found).

**Comment by xobotyi** [comment] 2019-08-19 04:50
@streamich maybe we should exclude `react-wait` from default export and add `react-wait` and `@types/react-wait` to the `optionalDependencies`?

**Comment by streamich** [comment] 2019-08-19 15:58
`react-wait` types are now re-expoted, it works for me with Webpack.

@dcporter do see errors caused by `react-wait` when using latest version? What is your setup?

**Comment by dcporter** [comment] 2019-09-03 13:40
Looks good now, I'm able to import hooks from root! This presented as a binary "everything works or everything is broken" situation, so I'm confident that everything is in a stable place now.

Thanks a ton. (I realized that this is not my issue so I can't close it. But @j-f1 can!)

**Closed** 2019-09-03 13:57 UTC
Labels: bug
